server:
  port: 8081
spring:
  application:
    name: proxy
  zipkin:
    storage:
      type: mysql
    base-url: http://localhost:9411
  sleuth:
    sampler:
    probability: 1.0

logging:
  pattern:
    console: "%d{ISO8601} traceId:%X{traceId} spanId:%X{spanId} %-5level %logger{0}.%M:%L - %msg %n"
